// <auto-generated />
using System;
using Arkive.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arkive.Data.Migrations
{
    [DbContext(typeof(ArkiveDbContext))]
    [Migration("20260203151604_AddLastModifiedDateTimeToSharePointSites")]
    partial class AddLastModifiedDateTimeToSharePointSites
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Arkive.Core.Models.ArchiveOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Archive");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ClientTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("DestinationPath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("FileMetadataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MspOrgId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("TargetTier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Cool");

                    b.Property<string>("VetoReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("VetoedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("VetoedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("FileMetadataId")
                        .HasDatabaseName("IX_ArchiveOperations_FileMetadataId");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasDatabaseName("IX_ArchiveOperations_OperationId");

                    b.HasIndex("ClientTenantId", "Status")
                        .HasDatabaseName("IX_ArchiveOperations_ClientTenantId_Status");

                    b.ToTable("ArchiveOperations", (string)null);
                });

            modelBuilder.Entity("Arkive.Core.Models.ArchiveRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("ClientTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("MspOrgId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TargetTier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Cool");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.HasKey("Id");

                    b.HasIndex("ClientTenantId", "IsActive")
                        .HasDatabaseName("IX_ArchiveRules_ClientTenantId_IsActive");

                    b.HasIndex("ClientTenantId", "RuleType")
                        .HasDatabaseName("IX_ArchiveRules_ClientTenantId_RuleType");

                    b.ToTable("ArchiveRules", (string)null);
                });

            modelBuilder.Entity("Arkive.Core.Models.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ClientTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MspOrgId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.HasKey("Id");

                    b.HasIndex("Action", "Timestamp")
                        .HasDatabaseName("IX_AuditEntries_Action_Timestamp");

                    b.HasIndex("ClientTenantId", "Timestamp")
                        .HasDatabaseName("IX_AuditEntries_ClientTenantId_Timestamp");

                    b.HasIndex("MspOrgId", "Timestamp")
                        .HasDatabaseName("IX_AuditEntries_MspOrgId_Timestamp");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("Arkive.Core.Models.ClientTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<bool?>("AuditLogAvailable")
                        .HasColumnType("bit");

                    b.Property<int?>("AutoApprovalDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(7);

                    b.Property<DateTimeOffset?>("ConnectedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("LastScannedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("M365TenantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<Guid>("MspOrgId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ReviewFlagged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ScanScheduleTimezone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.HasKey("Id");

                    b.HasIndex("MspOrgId", "M365TenantId")
                        .IsUnique()
                        .HasDatabaseName("IX_ClientTenants_MspOrgId_M365TenantId");

                    b.ToTable("ClientTenants", (string)null);
                });

            modelBuilder.Entity("Arkive.Core.Models.FileMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("ArchiveStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active");

                    b.Property<string>("BlobTier")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ClientTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("DriveId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("LastAccessedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<Guid>("MspOrgId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Owner")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("ScannedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("SizeBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.HasIndex("ClientTenantId", "ArchiveStatus")
                        .HasDatabaseName("IX_FileMetadata_ClientTenantId_ArchiveStatus");

                    b.HasIndex("ClientTenantId", "LastAccessedAt")
                        .HasDatabaseName("IX_FileMetadata_ClientTenantId_LastAccessedAt");

                    b.HasIndex("ClientTenantId", "SiteId")
                        .HasDatabaseName("IX_FileMetadata_ClientTenantId_SiteId");

                    b.HasIndex("ClientTenantId", "SiteId", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("IX_FileMetadata_ClientTenantId_SiteId_ItemId");

                    b.ToTable("FileMetadata", (string)null);
                });

            modelBuilder.Entity("Arkive.Core.Models.MonthlySavingsSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<long>("ArchivedStorageBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<Guid?>("ClientTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<Guid>("MspOrgId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SavingsAchieved")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SavingsPotential")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("StaleStorageBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalStorageBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClientTenantId");

                    b.HasIndex("MspOrgId", "Month")
                        .HasDatabaseName("IX_MonthlySavingsSnapshots_Org_Month");

                    b.HasIndex("MspOrgId", "ClientTenantId", "Month")
                        .IsUnique()
                        .HasDatabaseName("IX_MonthlySavingsSnapshots_Org_Tenant_Month")
                        .HasFilter("[ClientTenantId] IS NOT NULL");

                    b.ToTable("MonthlySavingsSnapshots", (string)null);
                });

            modelBuilder.Entity("Arkive.Core.Models.MspOrganization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("EntraIdTenantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SubscriptionTier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.HasKey("Id");

                    b.HasIndex("EntraIdTenantId")
                        .IsUnique()
                        .HasDatabaseName("IX_MspOrganizations_EntraIdTenantId");

                    b.ToTable("MspOrganizations", (string)null);
                });

            modelBuilder.Entity("Arkive.Core.Models.ReportSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("ClientTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("MspOrgId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReportJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ClientTenantId");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_ReportSnapshots_Token");

                    b.HasIndex("MspOrgId", "ClientTenantId")
                        .HasDatabaseName("IX_ReportSnapshots_Org_Tenant");

                    b.ToTable("ReportSnapshots", (string)null);
                });

            modelBuilder.Entity("Arkive.Core.Models.SharePointSite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("ClientTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<bool>("IsSelected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastModifiedDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("MspOrgId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("StorageUsedBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ClientTenantId", "IsSelected")
                        .HasDatabaseName("IX_SharePointSites_ClientTenantId_IsSelected");

                    b.HasIndex("ClientTenantId", "SiteId")
                        .IsUnique()
                        .HasDatabaseName("IX_SharePointSites_ClientTenantId_SiteId");

                    b.ToTable("SharePointSites", (string)null);
                });

            modelBuilder.Entity("Arkive.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("EntraIdObjectId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<Guid>("MspOrgId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.HasKey("Id");

                    b.HasIndex("EntraIdObjectId")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_EntraIdObjectId");

                    b.HasIndex("MspOrgId")
                        .HasDatabaseName("IX_Users_MspOrgId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Arkive.Core.Models.ArchiveOperation", b =>
                {
                    b.HasOne("Arkive.Core.Models.ClientTenant", "ClientTenant")
                        .WithMany()
                        .HasForeignKey("ClientTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arkive.Core.Models.FileMetadata", "FileMetadata")
                        .WithMany()
                        .HasForeignKey("FileMetadataId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ClientTenant");

                    b.Navigation("FileMetadata");
                });

            modelBuilder.Entity("Arkive.Core.Models.ArchiveRule", b =>
                {
                    b.HasOne("Arkive.Core.Models.ClientTenant", "ClientTenant")
                        .WithMany()
                        .HasForeignKey("ClientTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientTenant");
                });

            modelBuilder.Entity("Arkive.Core.Models.AuditEntry", b =>
                {
                    b.HasOne("Arkive.Core.Models.ClientTenant", "ClientTenant")
                        .WithMany()
                        .HasForeignKey("ClientTenantId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Arkive.Core.Models.MspOrganization", "MspOrganization")
                        .WithMany()
                        .HasForeignKey("MspOrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientTenant");

                    b.Navigation("MspOrganization");
                });

            modelBuilder.Entity("Arkive.Core.Models.ClientTenant", b =>
                {
                    b.HasOne("Arkive.Core.Models.MspOrganization", "MspOrganization")
                        .WithMany("ClientTenants")
                        .HasForeignKey("MspOrgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MspOrganization");
                });

            modelBuilder.Entity("Arkive.Core.Models.FileMetadata", b =>
                {
                    b.HasOne("Arkive.Core.Models.ClientTenant", "ClientTenant")
                        .WithMany("FileMetadata")
                        .HasForeignKey("ClientTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientTenant");
                });

            modelBuilder.Entity("Arkive.Core.Models.MonthlySavingsSnapshot", b =>
                {
                    b.HasOne("Arkive.Core.Models.ClientTenant", "ClientTenant")
                        .WithMany()
                        .HasForeignKey("ClientTenantId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Arkive.Core.Models.MspOrganization", "MspOrganization")
                        .WithMany()
                        .HasForeignKey("MspOrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientTenant");

                    b.Navigation("MspOrganization");
                });

            modelBuilder.Entity("Arkive.Core.Models.ReportSnapshot", b =>
                {
                    b.HasOne("Arkive.Core.Models.ClientTenant", "ClientTenant")
                        .WithMany()
                        .HasForeignKey("ClientTenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Arkive.Core.Models.MspOrganization", "MspOrganization")
                        .WithMany()
                        .HasForeignKey("MspOrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientTenant");

                    b.Navigation("MspOrganization");
                });

            modelBuilder.Entity("Arkive.Core.Models.SharePointSite", b =>
                {
                    b.HasOne("Arkive.Core.Models.ClientTenant", "ClientTenant")
                        .WithMany("SharePointSites")
                        .HasForeignKey("ClientTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientTenant");
                });

            modelBuilder.Entity("Arkive.Core.Models.User", b =>
                {
                    b.HasOne("Arkive.Core.Models.MspOrganization", "MspOrganization")
                        .WithMany("Users")
                        .HasForeignKey("MspOrgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MspOrganization");
                });

            modelBuilder.Entity("Arkive.Core.Models.ClientTenant", b =>
                {
                    b.Navigation("FileMetadata");

                    b.Navigation("SharePointSites");
                });

            modelBuilder.Entity("Arkive.Core.Models.MspOrganization", b =>
                {
                    b.Navigation("ClientTenants");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
